public enum TokenType
{
  LEFT_PAREM, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
  BANG, BANG_EQ, EQ, EQ_EQ, GREATER, GREATER_EQ, LESS, LESS_EQ,
  IDENTIFIER, STRING, NUMBER,
  AND, OR, IF, ELSE, FUN, FOR, CLASS, NIL, PRINT, RETURN, SUPER, THIS, TRUE, FALSE, VAR, WHILE, EOF
}